# Generated by Django 5.0.4 on 2024-05-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.CharField(max_length=255)),
                ('product_variant_one', models.CharField(max_length=255)),
                ('product_variant_two', models.CharField(max_length=255)),
                ('varient_title1', models.CharField(max_length=255)),
                ('varient_title2', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('stock', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
